### PR TITLE
Update bn.js

### PR DESCRIPTION
**Pull request by guybedford**

### CODE REVIEW

**Comment by guybedford** [comment]
See also:
- https://github.com/indutny/asn1.js/pull/30
- https://github.com/calvinmetcalf/browserify-sign/pull/5
- https://github.com/calvinmetcalf/createECDH/pull/1
- https://github.com/calvinmetcalf/diffie-hellman/pull/4
- https://github.com/indutny/elliptic/pull/14

If it doesn't make sense to update all of these, perhaps `public-encrypt` and `browserify-rsa` can be reverted to 0.15? I understand the upgrade paths will involve forks often, but it would be nice to minimize ecosystem forks of stable primary releases.

**Comment by indutny** [comment]
Landed in bb85f55. Btw, I thought that having `^` means that npm will update minor and patch versions automatically. Isn't it true?

**Comment by guybedford** [comment]
Thanks!

`^` for `0.x.x` versions means only auto-update the patch version. And for `0.0.x` it is the same as a full lock. See https://github.com/npm/node-semver#caret-ranges-123-025-004.

**Comment by indutny** [comment]
Ah, I see. It should be 1.x.x to work this way...

**Comment by indutny** [comment]
Thanks!

**Comment by guybedford** [comment]
Awesome, thanks for the quick response!

**Comment by andrey-p** [comment]
Wouldn't it be a better idea to have `bn.js` as a regular dependency rather than a peerDependency? I was under the impression that it was built for plugin-type relationships: http://blog.nodejs.org/2013/02/07/peer-dependencies/

(I'm only writing this because this change somehow bubbled down the dependency chain and broke my browserify install - I assume it's causing problems for quite a few more people too.)

**Pull request closed without merging**
