### PR TITLE
Make bn.js a normal dependency

### LINKED ISSUE #1049: Error during install
Just saying, currently I get this:

```
❯ npm i browserify
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "browserify"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package bn.js does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer miller-rabin@1.1.2 wants bn.js@^0.16.0
```

I understand it's not an issue in Browserify itself, but some dependencies. Looking into it a bit, I'm seeing @guybedford is [having a go at it](https://github.com/guybedford?tab=activity). I've opened this issue so other people know about it if they search when having the same issue.

### PR DESCRIPTION
**Pull request by guybedford**
This should fix https://github.com/substack/node-browserify/issues/1049.

### CODE REVIEW

**Comment by DavidSouther** [comment]
This is a huge issue for anyone using browserify or https://github.com/calvinmetcalf/diffie-hellman, please fix ASAP.

**Comment by JakeSidSmith** [comment]
:+1:

**Comment by JakeSidSmith** [comment]
:+1:

**Comment by indutny** [comment]
Oh gosh, I missed this.

**Comment by indutny** [comment]
Landed in bacc26f

**Comment by indutny** [comment]
Thanks.

**Pull request closed without merging**
